version: '3.9'

networks:
  proxy:
    external: true

services:
  reverse-proxy:
    container_name: traefic
    image: traefik:v2.8
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      #- "8080:8080"
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ssl-certs:/ssl-certs
    networks:
        - proxy
  ### example simple service
  # whoami:
  #   image: "traefik/whoami"
  #   container_name: "simple-service"
  #   networks:
  #     - traefic
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`${HOST}`)"
  #     - "traefik.http.routers.whoami.entrypoints=web,websecure"
  #     - "traefik.http.routers.whoami.tls=true"
  #     - "traefik.http.routers.whoami.tls.certresolver=production"

volumes:
  traefik-ssl-certs:
    driver: local